# Generated by Django 4.1.7 on 2024-02-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='email',
        ),
    ]
