# Generated by Django 4.1.7 on 2024-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_emp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('picture', models.ImageField(upload_to='tstimonials/')),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
